name: Java CD with Gradlew

on:
  workflow_run:
    workflows: [Java CI with Gradle]
    types: [completed]

jobs:
    on-success:
      runs-on: ubuntu-20.04
      permissions:
        contents: read
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      steps:
        - run: echo 'The triggering workflow passed'
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Configurar AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1