name: Java CD with Gradlew

on:
  workflow_run:
    workflows: [Java CI with Gradle]
    types: [completed]

jobs:
    on-success:
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      steps:
        - run: echo 'The triggering workflow passed'
    on-failure:
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'failure' }}
      steps:
        - run: echo 'The triggering workflow failed'